### ISSUE TITLE
Unable to install cronsim 2.6 version using serverless

### ISSUE THREAD

**Issue by viccsjain** [cuu508/cronsim#4]
Hi Team,

I am trying to use cronsim in my serverless project. I am using serverless 3.39.0 version.
I am also using serverless-python-requirements to install dependencies. But it fails with following error

ERROR: Could not find a version that satisfies the requirement cronsim==2.6 (from versions: 2.0)
ERROR: No matching distribution found for cronsim==2.6

Can you please help with this ?

**Comment by cuu508** [comment]
I can install cronsim on my local system into a virtualenv using pip:

```
$ python3 -m venv venv
$ source venv/bin/activate
(venv) $ pip install --no-cache-dir cronsim
Collecting cronsim
  Downloading cronsim-2.6.tar.gz (20 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: cronsim
  Building wheel for cronsim (pyproject.toml) ... done
  Created wheel for cronsim: filename=cronsim-2.6-py3-none-any.whl size=13492 sha256=73e1b99accc93ab3f45fd60e1543029e5d3c6b858fba34134a10a9f80d50546d
  Stored in directory: /tmp/pip-ephem-wheel-cache-x7tsey6a/wheels/33/a0/f0/3593ac488ca1779ccb82aa49c382a2c26d1f1a83bf9e6d5b47
Successfully built cronsim
Installing collected packages: cronsim
Successfully installed cronsim-2.6
```

As you can see from the output, pip downloads a source package and builds a wheel. 
Does `serverless-python-requirements` only work with wheels, and not with source packages?

**Comment by viccsjain** [comment]
Thanks for your response @cuu508 

It works with normal pip install, but fails with following command:

pip install --platform manylinux2014_x86_64 cronsim==2.6 --only-binary=:all: -t target
ERROR: Could not find a version that satisfies the requirement cronsim==2.6 (from versions: 2.0)
ERROR: No matching distribution found for cronsim==2.6

This command is generated internally by serverless.

**Comment by cuu508** [comment]
Ah, I see, this is because of the `--only-binary=:all:` parameter. I had only uploaded a source distribution to PyPI, and not a built distribution (.whl). 

I just uploaded a .whl as well, could you try again now?

**Comment by viccsjain** [comment]
Thanks for the quick turnaround. It worked this time.
